spring:
  kafka:
    bootstrap-servers: localhost:9092, localhost:9093
    producer:
      key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      value-deserializer: "org.springframework.kafka.support.serializer.ErrorHandlingDeserializer"
      properties:
        spring.deserializer.value.delegate.class: "org.springframework.kafka.support.serializer.JsonDeserializer"
        "[spring.json.value.default.type]": "com.nordstrom.itemplanning.location.dto.StorePayload"
    topic:
      name: transactions-topic
      partitions: 3
      replicas: 1